
export const cityPostcodes: Record<string, string> = {
    // Major Cities
    // Major Cities (Removed standalone per user request)
    "Salford (Manchester)": "M50 2EQ",
    "Aberdeen (Aberdeenshire)": "AB10 1AA",
    "Portsmouth (Hampshire)": "PO1 1AA",
    "York (North Yorkshire)": "YO1 6GA",
    "Peterborough (Cambridgeshire)": "PE1 1AA",
    "Dundee (Angus)": "DD1 1AA",
    "Oxford (Oxfordshire)": "OX1 1AA",
    "Cambridge (Cambridgeshire)": "CB1 1AA",
    // Major Cities

    // Large Towns & Cities
    "Leighton Buzzard (Bedfordshire)": "LU7 1AA",
    "Ashford (Kent)": "TN23 1AA",
    "Luton (Bedfordshire)": "LU1 2BN",
    "Milton Keynes (Buckinghamshire)": "MK9 1AA",
    "Northampton (Northamptonshire)": "NN1 1AA",
    "Bournemouth (Dorset)": "BH1 1AA",
    "Reading (Berkshire)": "RG1 1AA",
    "Blackpool (Lancashire)": "FY1 1AA",
    "Preston (Lancashire)": "PR1 1AA",
    "Huddersfield (Leeds)": "HD1 1AA",
    "Slough (Berkshire)": "SL1 1AA",
    "Swindon (Wiltshire)": "SN1 1AA",
    "Bolton (Manchester)": "BL1 1SA",
    "Oldham (Manchester)": "OL1 1AA",
    "Rochdale (Manchester)": "OL16 1AA",
    "Doncaster (Sheffield)": "DN1 1AA",
    "Bedford (Bedfordshire)": "MK40 1AA",
    "Ipswich (Suffolk)": "IP1 1AA",
    "Cheltenham (Gloucestershire)": "GL50 1AA",
    "Gloucester (Gloucestershire)": "GL1 1AA",
    "Worcester (Worcestershire)": "WR1 1AA",
    "Hereford (Herefordshire)": "HR1 2AA",
    "Shrewsbury (Shropshire)": "SY1 1AA",
    "Telford (Shropshire)": "TF3 4NT",
    "Canterbury (Kent)": "CT1 2YA",
    "Carlisle (Cumbria)": "CA3 8AN",
    "Chelmsford (Essex)": "CM1 1AA",
    "Chester (Cheshire)": "CH1 2HJ",
    "Colchester (Essex)": "CO1 1JG",
    "Durham (County Durham)": "DH1 3NJ",
    "Lancaster (Lancashire)": "LA1 1AA",
    "Lincoln (Lincolnshire)": "LN1 1AA",
    "Southend-on-Sea (Essex)": "SS1 1AA",
    "St Albans (Hertfordshire)": "AL1 3PG",
    "Truro (Cornwall)": "TR1 2LL",
    "Wakefield (Leeds)": "WF1 1AA",
    "Winchester (Hampshire)": "SO23 9BE",
    "Westminster (London)": "SW1A 1AA",
    "Warrington (Cheshire)": "WA1 1AA",
    "Wigan (Manchester)": "WN1 1AA",
    "Middlesbrough (North Yorkshire)": "TS1 1AA",
    "Barnsley (Sheffield)": "S70 1AA",
    "Newport (Cardiff)": "NP20 1AA",
    "Poole (Dorset)": "BH15 1AA",
    "Stockport (Manchester)": "SK1 1AA",
    "Basildon (Essex)": "SS14 1AA",
    "Maidstone (Kent)": "ME14 1AA",
    "Crawley (West Sussex)": "RH10 1AA",
    "Worthing (West Sussex)": "BN11 1AA",
    "Sutton Coldfield (Birmingham)": "B72 1AA",
    "Dudley (Birmingham)": "DY1 1AA",
    "Walsall (Birmingham)": "WS1 1AA",
    "Watford (Hertfordshire)": "WD17 1AA",
    "High Wycombe (Buckinghamshire)": "HP11 1AA",
    "Harlow (Essex)": "CM20 1AA",
    "Stevenage (Hertfordshire)": "SG1 1AA",
    "Redditch (Worcestershire)": "B97 4AA",
    "Chesterfield (Sheffield)": "S40 1AA",
    "Mansfield (Nottinghamshire)": "NG18 1AA",
    "Beeston (Nottinghamshire)": "NG9 1AA",
    "Loughborough (Leicestershire)": "LE11 1AA",
    "Burton upon Trent (Staffordshire)": "DE14 1AA",
    "Crewe (Cheshire)": "CW1 2BD",
    "Macclesfield (Cheshire)": "SK11 6BA",
    "Scunthorpe (Lincolnshire)": "DN15 6AA",
    "Grimsby (Lincolnshire)": "DN31 1AA",
    "Harrogate (North Yorkshire)": "HG1 1TE",
    "Halifax (Leeds)": "HX1 1AA",
    "Batley (Leeds)": "WF17 5DA",
    "Keighley (Leeds)": "BD21 3AA",
    "South Shields (Tyne and Wear)": "NE33 1AA",
    "Gateshead (Tyne and Wear)": "NE8 1AA",
    "Darlington (County Durham)": "DL1 5AD",
    "Hartlepool (County Durham)": "TS24 7DA",
    "Stockton-on-Tees (County Durham)": "TS18 1AA",
    "Hemel Hempstead (Hertfordshire)": "HP1 1AA",
    "Gillingham (Kent)": "ME7 1AA",
    "Eastbourne (East Sussex)": "BN21 1AA",
    "Rayleigh (Essex)": "SS6 7EW",
    "Lowestoft (Suffolk)": "NR32 1AA",
    "Woking (Surrey)": "GU21 6BG",
    "Maidenhead (Berkshire)": "SL6 1AA",
    "Basingstoke (Hampshire)": "RG21 4AA",
    "Fareham (Hampshire)": "PO16 7AA",
    "Gosport (Hampshire)": "PO12 1AA",
    "Ewell (Surrey)": "KT17 1TN",
    "Crosby (Liverpool)": "L23 2SE",
    "Paignton (Devon)": "TQ3 3AA",
    "Torquay (Devon)": "TQ1 1AA",
    "Bebington (Liverpool)": "CH63 7PG",
    "Halesowen (West Midlands)": "B63 3AQ",
    "Kidderminster (Worcestershire)": "DY10 1AA",
    "Rugby (Warwickshire)": "CV21 2AA",
    "Leamington Spa (Warwickshire)": "CV32 4AA",
    "Kettering (Northamptonshire)": "NN16 0AA",
    "Wellingborough (Northamptonshire)": "NN8 1AA",
    "Dunstable (Bedfordshire)": "LU6 1AA",
    "Aylesbury (Buckinghamshire)": "HP20 1AA",
    "Cheshunt (Hertfordshire)": "EN8 9XQ",
    "Welwyn Garden City (Hertfordshire)": "AL8 6AE",
    "Margate (Kent)": "CT9 1AA",
    "Royal Tunbridge Wells (Kent)": "TN1 1AA",
    "Leighton Buzzard (Bedfordshire)": "LU7 1AA",
    "Ashford (Kent)": "TN23 1AA",
    "Braintree (Essex)": "CM7 3AA",
    "Canvey Island (Essex)": "SS8 7AA",
    "Clacton-on-Sea (Essex)": "CO15 1AA",
    "Sittingbourne (Kent)": "ME10 1AA",
    "Gravesend (Kent)": "DA12 1AA",
    "Dartford (Kent)": "DA1 1AA",
    "Weymouth (Dorset)": "DT4 8AA",
    "Falmouth (Cornwall)": "TR11 2AA",
    "St Austell (Cornwall)": "PL25 4AA",
    "Scarborough (North Yorkshire)": "YO11 2AA",
    "Bridlington": "YO15 2AA",
    "Castleford (Leeds)": "WF10 1AA",
    "Pontefract (Leeds)": "WF8 1AA",
    "Rotherham (Sheffield)": "S60 1AA",
    "Sale (Manchester)": "M33 7AA",
    "Widnes (Cheshire)": "WA8 6AA",
    "Runcorn (Cheshire)": "WA7 1AA",
    "Ellesmere Port (Cheshire)": "CH65 0AA",
    "Birkenhead (Liverpool)": "CH41 5NG",
    "Wallasey (Liverpool)": "CH45 4NS",
    "Barrow-in-Furness (Cumbria)": "LA14 1AA",
    "Workington (Cumbria)": "CA14 3EP",
    "Whitehaven (Cumbria)": "CA28 7EU",
    "Chorley (Lancashire)": "PR7 1AA",
    "Accrington (Lancashire)": "BB5 1AA",
    "Burnley (Lancashire)": "BB11 1AA",
    "Lytham St Annes (Lancashire)": "FY8 1AA",
    "Stafford (Staffordshire)": "ST16 1AA",
    "Bromsgrove (Worcestershire)": "B61 8DA",
    "Grantham (Lincolnshire)": "NG31 6AA",
    "Ely (Cambridgeshire)": "CB7 4AA",
    "Lichfield (Staffordshire)": "WS13 6AA",
    "Ripon (North Yorkshire)": "HG4 1AA",
    "Salisbury (Wiltshire)": "SP1 2AA",
    "Wells (Somerset)": "BA5 2PU",
    "Solihull (Birmingham)": "B91 3AA",
    "Guildford (Surrey)": "GU1 4AA",
    "Staines (Surrey)": "TW18 4AA",
    "Chatham (Kent)": "ME4 4AA",
    "Hastings (East Sussex)": "TN34 1AA",
    "Nuneaton (Warwickshire)": "CV11 4AA",
    "Tamworth (Staffordshire)": "B79 7AA",
    "Cannock (Staffordshire)": "WS11 1AA",
    "Bath (Bristol)": "BA1 1AA",

    // London Boroughs & Districts
    "Brixton (London)": "SW2 1AA",
    "Hackney (London)": "E8 1AA",
    "Camden (London)": "NW1 8QL",
    "Islington (London)": "N1 1AA",
    "Greenwich (London)": "SE10 9NN",
    "Chelsea (London)": "SW3 1AA",
    "Wembley (London)": "HA9 0AA",
    "Croydon (London)": "CR0 1AA",
    "Ealing (London)": "W5 2AA",
    "Enfield (London)": "EN1 1AA",
    "Harrow (London)": "HA1 1AA",
    "Hounslow (London)": "TW3 1AA",
    "Kingston (London)": "KT1 1AA",
    "Merton (London)": "SW19 1AA",
    "Newham (London)": "E6 1AA",
    "Redbridge (London)": "IG1 1AA",
    "Richmond (London)": "TW9 1AA",
    "Southwark (London)": "SE1 1AA",
    "Tower Hamlets (London)": "E1 0AA",
    "Waltham Forest (London)": "E17 4AA",
    "Wandsworth (London)": "SW18 2PU",
    "Woolwich (London)": "SE18 6EU",
    "Fulham (London)": "SW6 1AA",

    // Northern Ireland
    "Derry (County Londonderry)": "BT48 6DS",
    "Lisburn (County Antrim)": "BT28 1XN",
    "Bangor (County Down)": "BT20 4BT",

    // Scotland Additional
    "Inverness (Highlands)": "IV1 1AA",
    "Perth (Perthshire)": "PH1 5PL",
    "Stirling (Stirlingshire)": "FK8 2DT",
    "Paisley (Glasgow)": "PA1 1AA",
    "East Kilbride (Glasgow)": "G74 1AA",
    "Livingston (Edinburgh)": "EH54 6AA",
    "Hamilton (Glasgow)": "ML3 6AA",
    "Cumbernauld (Glasgow)": "G67 1AA",
    "Dunfermline (Edinburgh)": "KY12 7AA",
    "Kirkcaldy (Edinburgh)": "KY1 1AA",
    "Ayr (Ayrshire)": "KA7 1AA",

    // Wales Additional
    "Wrexham (Clwyd)": "LL11 1AA",
    "Newport (Wales)": "NP20 1AA",
    "Bangor (Wales)": "LL57 1AA",
    "St Asaph (Denbighshire)": "LL17 0RD",
    "St Davids (Pembrokeshire)": "SA62 6SD",

    // England Additional
    "Chichester (West Sussex)": "PO19 1AA",

    // Missing Major Towns
    "Blackburn (Lancashire)": "BB1 1AA",
    "St Helens (Liverpool)": "WA10 1AA",
    "Bury (Manchester)": "BL9 0AA",
    "Southport (Liverpool)": "PR8 1AA",
    "West Bromwich (Birmingham)": "B70 8AA",
    "Taunton (Somerset)": "TA1 1AA",
    "Yeovil (Somerset)": "BA20 1AA",
    "Weston-super-Mare (Bristol)": "BS23 1AA",
    "Barnstaple (Devon)": "EX31 1AA",
    "Newquay (Cornwall)": "TR7 1AA",
    "Dover (Kent)": "CT16 1AA",
    "Folkestone (Kent)": "CT20 1AA",
    "Great Yarmouth (Norfolk)": "NR30 1AA",
    "King's Lynn (Norfolk)": "PE30 1AA",
    "Corby (Northamptonshire)": "NN17 1AA",
    "Redcar (North Yorkshire)": "TS10 1AA",
    "Tynemouth (Tyne and Wear)": "NE30 1AA",
    "Washington (Tyne and Wear)": "NE38 7AA",
    "Altrincham (Manchester)": "WA14 1AA",
    "Skelmersdale (Lancashire)": "WN8 6AA",
    "Morecambe (Lancashire)": "LA4 4AA",
    "Kendal (Cumbria)": "LA9 4AA",
    "Penrith (Cumbria)": "CA11 7AA",
    "Dumfries (Dumfriesshire)": "DG1 1AA",
    "Falkirk (Stirlingshire)": "FK1 1AA",
    "Kilmarnock (Ayrshire)": "KA1 1AA",
    "Motherwell (Glasgow)": "ML1 1AA",
    "Coatbridge (Glasgow)": "ML5 3AA",
    "Clydebank (Glasgow)": "G81 1AA",
    "Greenock (Renfrewshire)": "PA15 1AA",
    "Glenrothes (Fife)": "KY7 5AA",
    "Llandudno (Conwy)": "LL30 1AA",
    "Rhyl (Denbighshire)": "LL18 1AA",
    "Caerphilly (Cardiff)": "CF83 1AA",
    "Bridgend (Glamorgan)": "CF31 1AA",
    "Merthyr Tydfil (Glamorgan)": "CF47 8AA",
    "Cwmbran (Cardiff)": "NP44 1AA",
    "Barry (Cardiff)": "CF63 4AA",
    "Llanelli (Carmarthenshire)": "SA15 1AA",
    "Neath (Glamorgan)": "SA11 1AA",
    "Port Talbot (Glamorgan)": "SA12 6AA",
    "Newry (County Down)": "BT34 1AA",
    "Armagh (County Armagh)": "BT61 7AA",
    "Coleraine (County Londonderry)": "BT51 3AA",
    "Londonderry (County Londonderry)": "BT48 0AA",
    "Omagh (County Tyrone)": "BT78 1AA",
    "Enniskillen (County Fermanagh)": "BT74 7AA",

    // UK Counties
    "Lancashire": "PR1 1AA",
    "Yorkshire": "YO1 6GA",
    "Kent": "CT14 6AD",
    "Essex": "CM1 1AA",
    "Surrey": "GU1 1AA",
    "Sussex": "BN1 1AA",
    "Hampshire": "SO23 8UJ",
    "Cornwall": "TR1 1AA",
    "Devon": "EX1 1AA",
    "Somerset": "TA1 1AA",
    "Dorset": "DT1 1AA",
    "Wiltshire": "BA14 8JN",
    "Berkshire": "RG1 1AA",
    "Oxfordshire": "OX1 1AA",
    "Buckinghamshire": "HP20 1AA",
    "Hertfordshire": "SG13 8DE",
    "Bedfordshire": "MK40 1AA",
    "Cambridgeshire": "CB1 1AA",
    "Norfolk": "NR1 1AA",
    "Suffolk": "IP1 1AA",
    "Lincolnshire": "LN1 1AA",
    "Nottinghamshire": "NG1 1AA",
    "Derbyshire": "DE1 1AA",
    "Leicestershire": "LE1 1AA",
    "Northamptonshire": "NN1 1AA",
    "Warwickshire": "CV34 4SA",
    "Worcestershire": "WR1 1AA",
    "Gloucestershire": "GL1 1AA",
    "Herefordshire": "HR1 1AA",
    "Shropshire": "SY1 1AA",
    "Staffordshire": "ST16 1AA",
    "Cheshire": "CH1 1AA",
    "Northumberland": "NE61 1AA",
    "Cumbria": "CA1 1AA",
    "Newbury": "RG14 1AA",
    "Bracknell (Berkshire)": "RG12 1AA",
    "Uxbridge (London)": "UB8 1AA",
    "Bromley (London)": "BR1 1AA",
    "Kingston upon Thames (London)": "KT1 1AA",
    "Richmond upon Thames (London)": "TW9 1AA",
    "Tunbridge Wells (Kent)": "TN1 1AA",

    // --- DECONSTRUCTED MAJOR CITIES ---
    // London Boroughs
    "Camden (London)": "NW1 8QL",
    "Greenwich (London)": "SE10 9HZ",
    "Hackney (London)": "E8 1DY",
    "Hammersmith (London)": "W6 9JU",
    "Islington (London)": "N1 2UD",
    "Kensington (London)": "W8 4PX",
    "Lambeth (London)": "SW2 1RW",
    "Lewisham (London)": "SE6 4RU",
    "Southwark (London)": "SE1 2QH",
    "Tower Hamlets (London)": "E14 2BG",
    "Wandsworth (London)": "SW18 2PU",
    "Westminster (London)": "SW1E 6QP",
    "Barking (London)": "IG11 7LU",
    "Barnet (London)": "EN5 5XY",
    "Bexley (London)": "DA6 7AT",
    "Brent (London)": "HA9 0FJ",
    "Bromley (London)": "BR1 1DP",
    "Croydon (London)": "CR0 1EA",
    "Ealing (London)": "W5 2HL",
    "Enfield (London)": "EN1 3XY",
    "Haringey (London)": "N22 8HQ",
    "Harrow (London)": "HA1 2XY",
    "Havering (London)": "RM1 3BD",
    "Hillingdon (London)": "UB8 1UW",
    "Hounslow (London)": "TW3 3EB",
    "Kingston (London)": "KT1 1EU",
    "Merton (London)": "SM4 5DX",
    "Newham (London)": "E16 2QU",
    "Redbridge (London)": "IG1 1DD",
    "Richmond (London)": "TW9 1EZ",
    "Sutton (London)": "SM1 1EA",
    "Waltham Forest (London)": "E17 4JF",
    "Chelsea (London)": "SW3 5EE",
    "Fulham (London)": "SW6 1AA",
    // Manchester Boroughs
    "Salford (Manchester)": "M3 6AQ",
    "Bolton (Manchester)": "BL1 1RU",
    "Bury (Manchester)": "BL9 0SW",
    "Oldham (Manchester)": "OL1 1RA",
    "Rochdale (Manchester)": "OL16 1AB",
    "Stockport (Manchester)": "SK1 3XE",
    "Tameside (Manchester)": "OL6 6DU",
    "Trafford (Manchester)": "M32 0TH",
    "Wigan (Manchester)": "WN1 1YN",
    "Altrincham (Manchester)": "WA14 1PG",
    "Sale (Manchester)": "M33 7ZF",
    "Didsbury (Manchester)": "M20 2SG",
    "Chorlton (Manchester)": "M21 9DQ",
    "Fallowfield (Manchester)": "M14 6WN",
    "Withington (Manchester)": "M20 4BX",
    "Levenshulme (Manchester)": "M19 3PJ",
    "Wythenshawe (Manchester)": "M22 5RX",
    "Prestwich (Manchester)": "M25 1AN",
    "Radcliffe (Manchester)": "M26 2QZ",
    "Middleton (Manchester)": "M24 4DU",
    "Ashton-under-Lyne (Manchester)": "OL6 6DL",
    "Hyde (Manchester)": "SK14 1AL",
    "Stretford (Manchester)": "M32 9AY",
    "Urmston (Manchester)": "M41 0PN",
    "Eccles (Manchester)": "M30 0EP",
    "Swinton (Manchester)": "M27 4AA",
    // Birmingham Boroughs
    "Edgbaston (Birmingham)": "B15 2RU",
    "Sutton Coldfield (Birmingham)": "B73 6AA",
    "Aston (Birmingham)": "B6 6HE",
    "Bournville (Birmingham)": "B30 2AA",
    "Erdington (Birmingham)": "B24 8RE",
    "Harborne (Birmingham)": "B17 9NT",
    "Moseley (Birmingham)": "B13 8DD",
    "Selly Oak (Birmingham)": "B29 6HT",
    "Shirley (Birmingham)": "B90 3AL",
    "Smethwick (Birmingham)": "B66 3AQ",
    "Solihull (Birmingham)": "B91 3TB",
    "Walsall (Birmingham)": "WS1 1TP",
    "West Bromwich (Birmingham)": "B70 8JQ",
    "Wolverhampton (Birmingham)": "WV1 1RQ",
    "Dudley (Birmingham)": "DY1 1HF",
    "Stourbridge (Birmingham)": "DY8 1EQ",
    "Halesowen (Birmingham)": "B63 3AJ",
    "Oldbury (Birmingham)": "B69 3DB",
    "Rowley Regis (Birmingham)": "B65 9AH",
    "Tipton (Birmingham)": "DY4 8QL",
    "Wednesbury (Birmingham)": "WS10 7DF",
    "Brierley Hill (Birmingham)": "DY5 1TR",
    "Kings Heath (Birmingham)": "B14 7JZ",
    "Yardley (Birmingham)": "B25 8RN",
    // Leeds Boroughs
    "Headingley (Leeds)": "LS6 2AS",
    "Horsforth (Leeds)": "LS18 4AQ",
    "Roundhay (Leeds)": "LS8 2EA",
    "Chapel Allerton (Leeds)": "LS7 3PD",
    "Moortown (Leeds)": "LS17 6AA",
    "Pudsey (Leeds)": "LS28 7AB",
    "Morley (Leeds)": "LS27 9DY",
    "Garforth (Leeds)": "LS25 1DS",
    "Wetherby (Leeds)": "LS22 6NE",
    "Otley (Leeds)": "LS21 1BQ",
    "Yeadon (Leeds)": "LS19 7PP",
    "Guiseley (Leeds)": "LS20 8AH",
    "Rothwell (Leeds)": "LS26 0AD",
    "Kippax (Leeds)": "LS25 7AQ",
    "Bramley (Leeds)": "LS13 2EF",
    "Armley (Leeds)": "LS12 3AB",
    "Beeston (Leeds)": "LS11 8PN",
    "Hunslet (Leeds)": "LS10 1DT",
    "Middleton (Leeds)": "LS10 4AX",
    "Cross Gates (Leeds)": "LS15 8BA",
    "Bradford (Leeds)": "BD1 1HY",
    "Halifax (Leeds)": "HX1 1UJ",
    "Huddersfield (Leeds)": "HD1 2SY",
    "Wakefield (Leeds)": "WF1 1HQ",
    // Sheffield Boroughs
    "Crookes (Sheffield)": "S10 1UW",
    "Dore (Sheffield)": "S17 3GW",
    "Ecclesall (Sheffield)": "S11 8PR",
    "Fulwood (Sheffield)": "S10 3TD",
    "Hillsborough (Sheffield)": "S6 4HB",
    "Mosborough (Sheffield)": "S20 5AD",
    "Stannington (Sheffield)": "S6 6BP",
    "Walkley (Sheffield)": "S6 5AB",
    "Chapeltown (Sheffield)": "S35 2XD",
    "Stocksbridge (Sheffield)": "S36 1DT",
    "Handsworth (Sheffield)": "S13 9AZ",
    "Woodhouse (Sheffield)": "S13 7LY",
    "Gleadless (Sheffield)": "S12 2JS",
    "Meersbrook (Sheffield)": "S8 9FL",
    "Norton (Sheffield)": "S8 8JQ",
    "Beauchief (Sheffield)": "S8 7BB",
    "Rotherham (Sheffield)": "S60 1AE",
    "Barnsley (Sheffield)": "S70 2JG",
    "Doncaster (Sheffield)": "DN1 1AA",
    "Chesterfield (Sheffield)": "S40 1PB",
    // Bristol Boroughs
    "Clifton (Bristol)": "BS8 4AB",
    "Redland (Bristol)": "BS6 6AD",
    "Bishopston (Bristol)": "BS7 8AL",
    "Bedminster (Bristol)": "BS3 4EW",
    "Southville (Bristol)": "BS3 1AS",
    "Brislington (Bristol)": "BS4 5AH",
    "Kingswood (Bristol)": "BS15 8HR",
    "Filton (Bristol)": "BS34 7AF",
    "Patchway (Bristol)": "BS34 5NB",
    "Bradley Stoke (Bristol)": "BS32 8AH",
    "Keynsham (Bristol)": "BS31 1DQ",
    "Portishead (Bristol)": "BS20 6AQ",
    "Clevedon (Bristol)": "BS21 6AE",
    "Nailsea (Bristol)": "BS48 1AW",
    "Yate (Bristol)": "BS37 4AQ",
    "Thornbury (Bristol)": "BS35 2AR",
    "Staple Hill (Bristol)": "BS16 5HQ",
    "Fishponds (Bristol)": "BS16 3AA",
    "Frenchay (Bristol)": "BS16 1NB",
    "Westbury on Trym (Bristol)": "BS9 3ED",
    // Liverpool Boroughs
    "Anfield (Liverpool)": "L4 0TH",
    "Everton (Liverpool)": "L5 5BX",
    "Walton (Liverpool)": "L4 5SX",
    "Bootle (Liverpool)": "L20 3BA",
    "Crosby (Liverpool)": "L23 2TA",
    "Maghull (Liverpool)": "L31 0AH",
    "Kirkby (Liverpool)": "L32 8RD",
    "Huyton (Liverpool)": "L36 9UJ",
    "Prescot (Liverpool)": "L34 5PT",
    "St Helens (Liverpool)": "WA10 1HP",
    "Newton-le-Willows (Liverpool)": "WA12 9RU",
    "Haydock (Liverpool)": "WA11 0GD",
    "Widnes (Liverpool)": "WA8 7TF",
    "Runcorn (Liverpool)": "WA7 1AB",
    "Birkenhead (Liverpool)": "CH41 5AL",
    "Wallasey (Liverpool)": "CH44 1AQ",
    "Bebington (Liverpool)": "CH63 7PT",
    "Heswall (Liverpool)": "CH60 0AD",
    "Hoylake (Liverpool)": "CH47 2AB",
    "West Kirby (Liverpool)": "CH48 4DZ",
    "Aigburth (Liverpool)": "L17 8XW",
    "Allerton (Liverpool)": "L18 2DD",
    "Woolton (Liverpool)": "L25 7TD",
    "Garston (Liverpool)": "L19 2LQ",
    // Glasgow Boroughs
    "Partick (Glasgow)": "G11 6AA",
    "Hillhead (Glasgow)": "G12 8QQ",
    "Shawlands (Glasgow)": "G41 3DX",
    "Cathcart (Glasgow)": "G44 4ED",
    "Langside (Glasgow)": "G42 9JU",
    "Govan (Glasgow)": "G51 3TR",
    "Ibrox (Glasgow)": "G51 2YD",
    "Maryhill (Glasgow)": "G20 0EP",
    "Springburn (Glasgow)": "G21 1EA",
    "Dennistoun (Glasgow)": "G31 2PB",
    "Shettleston (Glasgow)": "G32 7NR",
    "Baillieston (Glasgow)": "G69 6NE",
    "Cambuslang (Glasgow)": "G72 7EE",
    "Rutherglen (Glasgow)": "G73 1AB",
    "Bearsden (Glasgow)": "G61 2SX",
    "Milngavie (Glasgow)": "G62 6PS",
    "Clydebank (Glasgow)": "G81 1TG",
    "Dumbarton (Glasgow)": "G82 1AA",
    "Paisley (Glasgow)": "PA1 1AA",
    "Renfrew (Glasgow)": "PA4 8UR",
    "Johnstone (Glasgow)": "PA5 8AA",
    "East Kilbride (Glasgow)": "G74 1AB",
    "Hamilton (Glasgow)": "ML3 6AU",
    "Motherwell (Glasgow)": "ML1 1AB",
    "Coatbridge (Glasgow)": "ML5 3AA",
    "Airdrie (Glasgow)": "ML6 6AA",
    "Cumbernauld (Glasgow)": "G67 1AA",
    // Edinburgh Boroughs
    "Leith (Edinburgh)": "EH6 6JU",
    "Morningside (Edinburgh)": "EH10 4DP",
    "Bruntsfield (Edinburgh)": "EH10 4EQ",
    "Marchmont (Edinburgh)": "EH9 1AE",
    "Newington (Edinburgh)": "EH8 9LY",
    "Stockbridge (Edinburgh)": "EH4 1JQ",
    "Corstorphine (Edinburgh)": "EH12 7TQ",
    "Murrayfield (Edinburgh)": "EH12 6HN",
    "Gorgie (Edinburgh)": "EH11 2AR",
    "Dalry (Edinburgh)": "EH11 2EB",
    "Portobello (Edinburgh)": "EH15 1AA",
    "Musselburgh (Edinburgh)": "EH21 6AA",
    "Dalkeith (Edinburgh)": "EH22 1AA",
    "Penicuik (Edinburgh)": "EH26 8AA",
    "Loanhead (Edinburgh)": "EH20 9AA",
    "Bonnyrigg (Edinburgh)": "EH19 2AA",
    "Currie (Edinburgh)": "EH14 5AA",
    "Balerno (Edinburgh)": "EH14 7AA",
    "Queensferry (Edinburgh)": "EH30 9AA",
    "Kirkliston (Edinburgh)": "EH29 9AA",
    "Broxburn (Edinburgh)": "EH52 5AA",
    "Livingston (Edinburgh)": "EH54 6EG",
    "Bathgate (Edinburgh)": "EH48 1AA",
    "Linlithgow (Edinburgh)": "EH49 7EQ",
    // Cardiff Boroughs
    "Canton (Cardiff)": "CF5 1AA",
    "Roath (Cardiff)": "CF24 3AA",
    "Cathays (Cardiff)": "CF24 4AA",
    "Splott (Cardiff)": "CF24 2AA",
    "Grangetown (Cardiff)": "CF11 7AA",
    "Riverside (Cardiff)": "CF11 9AA",
    "Pontcanna (Cardiff)": "CF11 9AA",
    "Llandaff (Cardiff)": "CF5 2AA",
    "Whitchurch (Cardiff)": "CF14 1AA",
    "Rhiwbina (Cardiff)": "CF14 6AA",
    "Llanishen (Cardiff)": "CF14 5AA",
    "Cyncoed (Cardiff)": "CF23 6AA",
    "Penylan (Cardiff)": "CF23 5AA",
    "Rumney (Cardiff)": "CF3 3AA",
    "Llanrumney (Cardiff)": "CF3 4AA",
    "St Mellons (Cardiff)": "CF3 0AA",
    "Ely (Cardiff)": "CF5 4AA",
    "Caerau (Cardiff)": "CF5 5AA",
    "Fairwater (Cardiff)": "CF5 3AA",
    "Radyr (Cardiff)": "CF15 8AA",
    "Penarth (Cardiff)": "CF64 1AA",
    "Barry (Cardiff)": "CF62 8AA",
    "Dinas Powys (Cardiff)": "CF64 4AA",
    "Llantwit Major (Cardiff)": "CF61 1AA",
    "Caerphilly (Cardiff)": "CF83 1AA",
    "Pontypridd (Cardiff)": "CF37 1AA",
    "Newport (Cardiff)": "NP20 1AA",
    "Cwmbran (Cardiff)": "NP44 1AA",
};

export function getPostcodeForCity(city: string): string {
    // Try direct match
    if (cityPostcodes[city]) return cityPostcodes[city];

    const normalizedKey = Object.keys(cityPostcodes).find(k => city.includes(k));
    if (normalizedKey) return cityPostcodes[normalizedKey];

    return ""; // Return empty if no match, allowing schema to omit it implies "unknown" rather than "fake"
}

