
export const cityPostcodes: Record<string, string> = {
    // Major Cities
    "London": "SW1A 1AA",
    "Manchester": "M1 1AE",
    "Birmingham": "B1 1BB",
    "Leeds": "LS1 1UR",
    "Glasgow": "G1 1RX",
    "Sheffield": "S1 2HH",
    "Bradford": "BD1 1US",
    "Liverpool": "L1 8JQ",
    "Edinburgh": "EH1 1YZ",
    "Bristol": "BS1 2AA",
    "Cardiff": "CF10 1AA",
    "Coventry": "CV1 1AA",
    "Nottingham": "NG1 1AA",
    "Leicester": "LE1 1AA",
    "Sunderland": "SR1 1AA",
    "Belfast": "BT1 5GS",
    "Newcastle upon Tyne": "NE1 1AA",
    "Newcastle-upon-Tyne": "NE1 1AA",
    "Brighton": "BN1 1AA",
    "Brighton & Hove": "BN1 1AA",
    "Hull": "HU1 1AA",
    "Plymouth": "PL1 1AA",
    "Stoke-on-Trent": "ST1 1AA",
    "Wolverhampton": "WV1 1AA",
    "Derby": "DE1 1AA",
    "Swansea": "SA1 1AA",
    "Southampton": "SO14 7SJ",
    "Salford": "M50 2EQ",
    "Aberdeen": "AB10 1AA",
    "Portsmouth": "PO1 1AA",
    "York": "YO1 6GA",
    "Peterborough": "PE1 1AA",
    "Dundee": "DD1 1AA",
    "Oxford": "OX1 1AA",
    "Cambridge": "CB1 1AA",
    "Norwich": "NR1 1AA",
    "Exeter": "EX1 1AA",

    // Large Towns & Cities
    "Luton": "LU1 2BN",
    "Milton Keynes": "MK9 1AA",
    "Northampton": "NN1 1AA",
    "Bournemouth": "BH1 1AA",
    "Reading": "RG1 1AA",
    "Blackpool": "FY1 1AA",
    "Preston": "PR1 1AA",
    "Huddersfield": "HD1 1AA",
    "Slough": "SL1 1AA",
    "Swindon": "SN1 1AA",
    "Bolton": "BL1 1SA",
    "Oldham": "OL1 1AA",
    "Rochdale": "OL16 1AA",
    "Doncaster": "DN1 1AA",
    "Bedford": "MK40 1AA",
    "Ipswich": "IP1 1AA",
    "Cheltenham": "GL50 1AA",
    "Gloucester": "GL1 1AA",
    "Worcester": "WR1 1AA",
    "Hereford": "HR1 2AA",
    "Shrewsbury": "SY1 1AA",
    "Telford": "TF3 4NT",
    "Canterbury": "CT1 2YA",
    "Carlisle": "CA3 8AN",
    "Chelmsford": "CM1 1AA",
    "Chester": "CH1 2HJ",
    "Colchester": "CO1 1JG",
    "Durham": "DH1 3NJ",
    "Lancaster": "LA1 1AA",
    "Lincoln": "LN1 1AA",
    "Southend-on-Sea": "SS1 1AA",
    "St Albans": "AL1 3PG",
    "Truro": "TR1 2LL",
    "Wakefield": "WF1 1AA",
    "Winchester": "SO23 9BE",
    "Westminster": "SW1A 1AA",
    "Warrington": "WA1 1AA",
    "Wigan": "WN1 1AA",
    "Middlesbrough": "TS1 1AA",
    "Barnsley": "S70 1AA",
    "Newport": "NP20 1AA",
    "Poole": "BH15 1AA",
    "Stockport": "SK1 1AA",
    "Basildon": "SS14 1AA",
    "Maidstone": "ME14 1AA",
    "Crawley": "RH10 1AA",
    "Worthing": "BN11 1AA",
    "Sutton Coldfield": "B72 1AA",
    "Dudley": "DY1 1AA",
    "Walsall": "WS1 1AA",
    "Watford": "WD17 1AA",
    "High Wycombe": "HP11 1AA",
    "Harlow": "CM20 1AA",
    "Stevenage": "SG1 1AA",
    "Redditch": "B97 4AA",
    "Chesterfield": "S40 1AA",
    "Mansfield": "NG18 1AA",
    "Beeston": "NG9 1AA",
    "Loughborough": "LE11 1AA",
    "Burton upon Trent": "DE14 1AA",
    "Crewe": "CW1 2BD",
    "Macclesfield": "SK11 6BA",
    "Scunthorpe": "DN15 6AA",
    "Grimsby": "DN31 1AA",
    "Harrogate": "HG1 1TE",
    "Halifax": "HX1 1AA",
    "Batley": "WF17 5DA",
    "Keighley": "BD21 3AA",
    "South Shields": "NE33 1AA",
    "Gateshead": "NE8 1AA",
    "Darlington": "DL1 5AD",
    "Hartlepool": "TS24 7DA",
    "Stockton-on-Tees": "TS18 1AA",
    "Hemel Hempstead": "HP1 1AA",
    "Gillingham": "ME7 1AA",
    "Eastbourne": "BN21 1AA",
    "Rayleigh": "SS6 7EW",
    "Lowestoft": "NR32 1AA",
    "Woking": "GU21 6BG",
    "Maidenhead": "SL6 1AA",
    "Basingstoke": "RG21 4AA",
    "Fareham": "PO16 7AA",
    "Gosport": "PO12 1AA",
    "Ewell": "KT17 1TN",
    "Crosby": "L23 2SE",
    "Paignton": "TQ3 3AA",
    "Torquay": "TQ1 1AA",
    "Bebington": "CH63 7PG",
    "Halesowen": "B63 3AQ",
    "Kidderminster": "DY10 1AA",
    "Rugby": "CV21 2AA",
    "Leamington Spa": "CV32 4AA",
    "Kettering": "NN16 0AA",
    "Wellingborough": "NN8 1AA",
    "Dunstable": "LU6 1AA",
    "Aylesbury": "HP20 1AA",
    "Cheshunt": "EN8 9XQ",
    "Welwyn Garden City": "AL8 6AE",
    "Margate": "CT9 1AA",
    "Royal Tunbridge Wells": "TN1 1AA",
    "Ashford": "TN23 1AA",
    "Braintree": "CM7 3AA",
    "Canvey Island": "SS8 7AA",
    "Clacton-on-Sea": "CO15 1AA",
    "Sittingbourne": "ME10 1AA",
    "Gravesend": "DA12 1AA",
    "Dartford": "DA1 1AA",
    "Weymouth": "DT4 8AA",
    "Falmouth": "TR11 2AA",
    "St Austell": "PL25 4AA",
    "Scarborough": "YO11 2AA",
    "Bridlington": "YO15 2AA",
    "Castleford": "WF10 1AA",
    "Pontefract": "WF8 1AA",
    "Rotherham": "S60 1AA",
    "Sale": "M33 7AA",
    "Widnes": "WA8 6AA",
    "Runcorn": "WA7 1AA",
    "Ellesmere Port": "CH65 0AA",
    "Birkenhead": "CH41 5NG",
    "Wallasey": "CH45 4NS",
    "Barrow-in-Furness": "LA14 1AA",
    "Workington": "CA14 3EP",
    "Whitehaven": "CA28 7EU",
    "Chorley": "PR7 1AA",
    "Accrington": "BB5 1AA",
    "Burnley": "BB11 1AA",
    "Lytham St Annes": "FY8 1AA",
    "Stafford": "ST16 1AA",
    "Bromsgrove": "B61 8DA",
    "Grantham": "NG31 6AA",
    "Ely": "CB7 4AA",
    "Lichfield": "WS13 6AA",
    "Ripon": "HG4 1AA",
    "Salisbury": "SP1 2AA",
    "Wells": "BA5 2PU",
    "Solihull": "B91 3AA",
    "Guildford": "GU1 4AA",
    "Staines": "TW18 4AA",
    "Chatham": "ME4 4AA",
    "Hastings": "TN34 1AA",
    "Nuneaton": "CV11 4AA",
    "Tamworth": "B79 7AA",
    "Cannock": "WS11 1AA",
    "Bath": "BA1 1AA",

    // London Boroughs & Districts
    "Brixton": "SW2 1AA",
    "Hackney": "E8 1AA",
    "Camden": "NW1 8QL",
    "Islington": "N1 1AA",
    "Greenwich": "SE10 9NN",
    "Chelsea": "SW3 1AA",
    "Wembley": "HA9 0AA",
    "Croydon": "CR0 1AA",
    "Ealing": "W5 2AA",
    "Enfield": "EN1 1AA",
    "Harrow": "HA1 1AA",
    "Hounslow": "TW3 1AA",
    "Kingston": "KT1 1AA",
    "Merton": "SW19 1AA",
    "Newham": "E6 1AA",
    "Redbridge": "IG1 1AA",
    "Richmond": "TW9 1AA",
    "Southwark": "SE1 1AA",
    "Tower Hamlets": "E1 0AA",
    "Waltham Forest": "E17 4AA",
    "Wandsworth": "SW18 2PU",
    "Woolwich": "SE18 6EU",
    "Fulham": "SW6 1AA",

    // Northern Ireland
    "Derry": "BT48 6DS",
    "Lisburn": "BT28 1XN",
    "Bangor": "BT20 4BT",

    // Scotland Additional
    "Inverness": "IV1 1AA",
    "Perth": "PH1 5PL",
    "Stirling": "FK8 2DT",
    "Paisley": "PA1 1AA",
    "East Kilbride": "G74 1AA",
    "Livingston": "EH54 6AA",
    "Hamilton": "ML3 6AA",
    "Cumbernauld": "G67 1AA",
    "Dunfermline": "KY12 7AA",
    "Kirkcaldy": "KY1 1AA",
    "Ayr": "KA7 1AA",

    // Wales Additional
    "Wrexham": "LL11 1AA",
    "Newport (Wales)": "NP20 1AA",
    "Bangor (Wales)": "LL57 1AA",
    "St Asaph": "LL17 0RD",
    "St Davids": "SA62 6SD",

    // England Additional
    "Chichester": "PO19 1AA",

    // Missing Major Towns
    "Blackburn": "BB1 1AA",
    "St Helens": "WA10 1AA",
    "Bury": "BL9 0AA",
    "Southport": "PR8 1AA",
    "West Bromwich": "B70 8AA",
    "Taunton": "TA1 1AA",
    "Yeovil": "BA20 1AA",
    "Weston-super-Mare": "BS23 1AA",
    "Barnstaple": "EX31 1AA",
    "Newquay": "TR7 1AA",
    "Dover": "CT16 1AA",
    "Folkestone": "CT20 1AA",
    "Great Yarmouth": "NR30 1AA",
    "King's Lynn": "PE30 1AA",
    "Corby": "NN17 1AA",
    "Redcar": "TS10 1AA",
    "Tynemouth": "NE30 1AA",
    "Washington": "NE38 7AA",
    "Altrincham": "WA14 1AA",
    "Skelmersdale": "WN8 6AA",
    "Morecambe": "LA4 4AA",
    "Kendal": "LA9 4AA",
    "Penrith": "CA11 7AA",
    "Dumfries": "DG1 1AA",
    "Falkirk": "FK1 1AA",
    "Kilmarnock": "KA1 1AA",
    "Motherwell": "ML1 1AA",
    "Coatbridge": "ML5 3AA",
    "Clydebank": "G81 1AA",
    "Greenock": "PA15 1AA",
    "Glenrothes": "KY7 5AA",
    "Llandudno": "LL30 1AA",
    "Rhyl": "LL18 1AA",
    "Caerphilly": "CF83 1AA",
    "Bridgend": "CF31 1AA",
    "Merthyr Tydfil": "CF47 8AA",
    "Cwmbran": "NP44 1AA",
    "Barry": "CF63 4AA",
    "Llanelli": "SA15 1AA",
    "Neath": "SA11 1AA",
    "Port Talbot": "SA12 6AA",
    "Newry": "BT34 1AA",
    "Armagh": "BT61 7AA",
    "Coleraine": "BT51 3AA",
    "Londonderry": "BT48 0AA",
    "Omagh": "BT78 1AA",
    "Enniskillen": "BT74 7AA",

    // UK Counties
    "Lancashire": "PR1 1AA",
    "Yorkshire": "YO1 6GA",
    "Kent": "CT14 6AD",
    "Essex": "CM1 1AA",
    "Surrey": "GU1 1AA",
    "Sussex": "BN1 1AA",
    "Hampshire": "SO23 8UJ",
    "Cornwall": "TR1 1AA",
    "Devon": "EX1 1AA",
    "Somerset": "TA1 1AA",
    "Dorset": "DT1 1AA",
    "Wiltshire": "BA14 8JN",
    "Berkshire": "RG1 1AA",
    "Oxfordshire": "OX1 1AA",
    "Buckinghamshire": "HP20 1AA",
    "Hertfordshire": "SG13 8DE",
    "Bedfordshire": "MK40 1AA",
    "Cambridgeshire": "CB1 1AA",
    "Norfolk": "NR1 1AA",
    "Suffolk": "IP1 1AA",
    "Lincolnshire": "LN1 1AA",
    "Nottinghamshire": "NG1 1AA",
    "Derbyshire": "DE1 1AA",
    "Leicestershire": "LE1 1AA",
    "Northamptonshire": "NN1 1AA",
    "Warwickshire": "CV34 4SA",
    "Worcestershire": "WR1 1AA",
    "Gloucestershire": "GL1 1AA",
    "Herefordshire": "HR1 1AA",
    "Shropshire": "SY1 1AA",
    "Staffordshire": "ST16 1AA",
    "Cheshire": "CH1 1AA",
    "Northumberland": "NE61 1AA",
    "Cumbria": "CA1 1AA",
    "Newbury": "RG14 1AA",
    "Bracknell": "RG12 1AA",
    "Uxbridge": "UB8 1AA",
    "Bromley": "BR1 1AA",
    "Kingston upon Thames": "KT1 1AA",
    "Richmond upon Thames": "TW9 1AA",
    "Tunbridge Wells": "TN1 1AA",
};

export function getPostcodeForCity(city: string): string {
    // Try direct match
    if (cityPostcodes[city]) return cityPostcodes[city];

    // Try fuzzy match (e.g. "Greater London" -> "London")
    const normalizedKey = Object.keys(cityPostcodes).find(k => city.includes(k));
    if (normalizedKey) return cityPostcodes[normalizedKey];

    return ""; // Return empty if no match, allowing schema to omit it implies "unknown" rather than "fake"
}
