/**
 * graph-knowledge — chat-side consumer of the Graphify DOMAIN knowledge graph.
 *
 * This is the RAG "improvement layer". It loads the public-safe domain graph
 * generated by `npm run graph:build` (trades / scenarios / safety actions /
 * authorities and their relationships) and lets the chat:
 *   - detect a trade as a graph-based FALLBACK when keyword matching misses, and
 *   - surface RELATED trades so answers feel smarter and more connected.
 *
 * It contains only already-public domain knowledge (no code, no file paths, no
 * secrets) so it is safe to ship to the browser. Every export is defensive and
 * returns a harmless default on any error — it must never break the chat.
 */
import domainGraph from "@/data/domain-graph.json";
import { trades } from "@/lib/trades";

type Region = "uk" | "us" | "usa" | "UK" | "US";

interface DomainNode {
    id: string;
    label: string;
    kind?: "trade" | "scenario" | "authority";
    keywords?: string[];
    risk_level?: string | null;
    action_plan?: string | null;
    trade?: string;
    region?: string | null;
    url?: string | null;
}
interface DomainEdge { source: string; target: string; relation: string; }
interface DomainGraph { nodes: DomainNode[]; edges: DomainEdge[]; meta?: { generatedAt?: string; commit?: string } }

const G = domainGraph as unknown as DomainGraph;

// ---- Indexes (built once) -------------------------------------------------
const nodeById = new Map<string, DomainNode>();
const relatedByTrade = new Map<string, Set<string>>();   // trade slug -> related trade slugs
const scenariosByTrade = new Map<string, DomainNode[]>(); // trade slug -> scenario nodes
const authoritiesByScenario = new Map<string, DomainNode[]>();

try {
    for (const n of G.nodes || []) nodeById.set(n.id, n);
    for (const e of G.edges || []) {
        if (e.relation === "related_to") {
            const a = e.source.replace(/^trade:/, "");
            const b = e.target.replace(/^trade:/, "");
            if (!relatedByTrade.has(a)) relatedByTrade.set(a, new Set());
            if (!relatedByTrade.has(b)) relatedByTrade.set(b, new Set());
            relatedByTrade.get(a)!.add(b);
            relatedByTrade.get(b)!.add(a); // treat as undirected for suggestions
        } else if (e.relation === "handles") {
            const trade = e.source.replace(/^trade:/, "");
            const sc = nodeById.get(e.target);
            if (sc) {
                if (!scenariosByTrade.has(trade)) scenariosByTrade.set(trade, []);
                scenariosByTrade.get(trade)!.push(sc);
            }
        } else if (e.relation.startsWith("governed_by")) {
            const auth = nodeById.get(e.target);
            if (auth) {
                if (!authoritiesByScenario.has(e.source)) authoritiesByScenario.set(e.source, []);
                authoritiesByScenario.get(e.source)!.push(auth);
            }
        }
    }
} catch { /* leave indexes empty; all functions degrade gracefully */ }

const isReady = nodeById.size > 0;

function displayName(slug: string, country?: "UK" | "US" | string): string {
    const t = trades.find((x) => x.slug === slug || x.slug === slug.replace("air-conditioning", "hvac"));
    if (!t) return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
    return country === "US" ? (t.usName || t.name) : t.name;
}

// ---------------------------------------------------------------------------
/** Graph-based trade detection. Use ONLY as a fallback — returns null on miss. */
export function graphDetectTrade(message: string): string | null {
    if (!isReady || !message) return null;
    try {
        const lower = ` ${message.toLowerCase()} `;
        let best: string | null = null;
        let bestScore = 0;
        for (const n of nodeById.values()) {
            if (n.kind !== "trade" || !n.keywords?.length) continue;
            let score = 0;
            for (const kw of n.keywords) {
                if (lower.includes(kw.toLowerCase())) score += kw.split(" ").length;
            }
            if (score > bestScore) { bestScore = score; best = n.id.replace(/^trade:/, ""); }
        }
        return bestScore > 0 ? best : null;
    } catch { return null; }
}

/** Related trades for a given trade slug (graph `related_to` neighbours). */
export function getRelatedTrades(slug: string): { slug: string; label: string }[] {
    if (!isReady || !slug) return [];
    try {
        const norm = slug === "hvac" ? "hvac" : slug;
        const set = relatedByTrade.get(norm);
        if (!set) return [];
        return [...set].map((s) => ({ slug: s, label: s.replace(/-/g, " ") }));
    } catch { return []; }
}

/**
 * A short, friendly markdown note suggesting related trades. Returns "" when
 * there's nothing useful to add, so callers can append it unconditionally.
 */
export function buildRelatedHelpNote(slug: string, country?: "UK" | "US" | string): string {
    try {
        const related = getRelatedTrades(slug);
        if (!related.length) return "";
        const names = related.slice(0, 2).map((r) => displayName(r.slug, country).toLowerCase());
        if (!names.length) return "";
        const list = names.length === 1 ? names[0] : `${names.slice(0, -1).join(", ")} or a ${names[names.length - 1]}`;
        return `\n\n*🔗 Related help: depending on the situation you may also need a ${list}.*`;
    } catch { return ""; }
}

/** Whether the domain graph loaded — handy for diagnostics/tests. */
export function isGraphReady(): boolean { return isReady; }

/** Metadata about when the domain graph was generated. */
export function getGraphMeta(): { generatedAt?: string; commit?: string } {
    try { return G.meta || {}; } catch { return {}; }
}
