
const data = `Email	FirstName	BusinessName	City	Trade	PricingLink
contactus@aedwardsroofingltd.co.uk	A	A Edwards Roofing Ltd Newport 24HR	Newport	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=Newport&ref=0ee816de-d311-47ab-bf29-0d4d0dfef2cc
hello@exeterheating.co.uk	Professional	Professional Plumbers Exeter	Exeter	plumber	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=plumber&city=Exeter&ref=4ecd06f6-5c96-37aa-9afa-bb1d6d4f8d44
info@chrissnellroofing.co.uk	Chris	Chris Snell Roofing Specialist Ltd	Salisbury	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=Salisbury&ref=00000000-0000-4000-a000-00001e641d8e
admin@bowconstruction.co.uk	Bow	Bow Construction LTD	Shrewsbury	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Shrewsbury&ref=bffe5450-1006-375b-b60e-cd4152c019f2
idealelectricalsolution@gmail.com	Ideal	Ideal Electrical Solutions	Liverpool	Electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=Electrician&city=Liverpool&ref=0a66129d-c2ad-3d96-9547-3d5ab554e2f1
info@comptecltd.co.uk	Comptec	Comptec Ltd	West Bromwich	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=West%20Bromwich&ref=00000000-0000-4000-a000-0000397247fd
neilhemmings1977@outlook.com	Redcar	Redcar Roofing And Maintenance	Redcar	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=Redcar&ref=00000000-0000-4000-a000-000022b2aa02
info@liverpooldrainagesolutions.co.uk	Liverpool	Liverpool Drainage Solutions	Liverpool	Drain Specialist	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=Drain%20Specialist&city=Liverpool&ref=4ea15359-ff76-3d64-90d5-0baaae2dd23a
info@cbsheating.co.uk	CBS	CBS Commercial Heating Ltd	Cheshunt	gas-engineer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=gas-engineer&city=Cheshunt&ref=00000000-0000-4000-a000-00004803ae94
excelllocksmith@live.co.uk	Excell	Excell Locksmiths	Cheshunt	locksmith	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=locksmith&city=Cheshunt&ref=00000000-0000-4000-a000-00007fb41f92
info@electricianssheffield247.co.uk	Express	Express Local Sheffield Electricians	Sheffield	Electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=Electrician&city=Sheffield&ref=55aaa156-8c32-3f06-ae41-61df07aa33b1
donaldsonlocksmiths@hotmail.com	Donaldson	Donaldson Locksmiths Ltd	Weymouth	locksmith	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=locksmith&city=Weymouth&ref=00000000-0000-4000-a000-000048b2e0ad
info@sacservices.co.uk	S	S A C Services Ltd	West Bromwich	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=West%20Bromwich&ref=00000000-0000-4000-a000-00002e7fb133
info@acmsltd.net	A	A C M S Ltd	West Bromwich	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=West%20Bromwich&ref=00000000-0000-4000-a000-000070bbaa4c
roofcheck@mail.com	Berridge	Berridge Roofing & Maintenance	Barry	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=Barry&ref=00000000-0000-4000-a000-0000182e64b1
info@carbreakdownservice.co.uk	CarBreakdownService.co.uk	CarBreakdownService.co.uk Seaford 24/7	Sussex	breakdown	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=breakdown&city=Sussex&ref=abe0e6f6-b490-4122-a10c-7f90ab1ce16a
info@redsrecovery.co.uk	Reds	Reds Recovery Services Ramsgate 24HR	Kent	breakdown	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=breakdown&city=Kent&ref=7e54346b-29b3-4d37-b15b-c223955129ca
info@sasrecovery.uk	SAS	SAS Recovery Tonbridge 24/7	Kent	breakdown	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=breakdown&city=Kent&ref=945c2f28-95f6-4963-a026-d30166898930
robertchambers627@btinternet.com	R	R C Electrical	Pontefract	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=Pontefract&ref=00000000-0000-4000-a000-00002e4872ee
paul@anotherplumber.co.uk	Another	Another Plumber	Pontefract	gas-engineer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=gas-engineer&city=Pontefract&ref=00000000-0000-4000-a000-000035bdca0a
info@airimprove.ltd.uk	Air	Air Improve Ltd	Winchester	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=Winchester&ref=00000000-0000-4000-a000-00002fee43d4
info@elsysltd.co.uk	ELSYS	ELSYS Ltd	High Wycombe	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=High%20Wycombe&ref=00000000-0000-4000-a000-0000498f3bd4
info@keys4ulocksmith.co.uk	Locksmith	Locksmith High Wycombe	High Wycombe	locksmith	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=locksmith&city=High%20Wycombe&ref=00000000-0000-4000-a000-00000354b6d8
info@basildonemergencyplumbing.co.uk	Basildon	Basildon Emergency Plumbing 24/7	Basildon	plumber	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=plumber&city=Basildon&ref=a553c0e9-1e89-46f3-8705-93970b244ebb
sales@homesecureukglaziers.co.uk	Homesecure	Homesecure UK Glaziers	Northampton	Glazier	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=Glazier&city=Northampton&ref=c701d198-6bf9-36bf-a8ce-e160a48213fd
info@fmb.org.uk	SOS-Man	SOS-Man 24/7 Sheffield	Sheffield	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Sheffield&ref=ff12e93b-382c-4dbf-ab63-5e157e4f8986
contact@rickslatteryplumbing.co.uk	Rick	Rick Slattery Plumbing & Heating	Blackpool	water-restoration	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=water-restoration&city=Blackpool&ref=9c2371ca-275e-340b-987e-fa458ac06fab
info@acornservices.com	Acorn	Acorn Building Services Edinburgh	Edinburgh	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Edinburgh&ref=9528334c-f507-48f7-bb29-75877dc8d61f
info@elextric.co.uk	Elextric	Elextric Electrical Services	Islington	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=Islington&ref=00000000-0000-4000-a000-00006bca035f
office@tm44.uk	TM44.UK	TM44.UK - Air Conditioning Inspections	Camden	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=Camden&ref=00000000-0000-4000-a000-0000787d6663
help@emergencyboardups.co.uk	Emergency	Emergency Boardups Coventry	Coventry	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Coventry&ref=168efb0a-f281-447d-9b66-a1b2334ee5bf
info@t-s-gas.co.uk	T	T S Gas & Electric Ltd	Dudley	gas-engineer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=gas-engineer&city=Dudley&ref=7190744b-d87d-320c-89f5-40c3d1b2caf5
info@md-drainagesolutions.co.uk	M&D	M&D Drainage Solutions 24/7	Dudley	drain-specialist	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=drain-specialist&city=Dudley&ref=3de31e78-6721-38b1-8305-7042ed991d11
info@rainbowrestoration.co.uk	Rainbow	Rainbow Restoration York	York	water-restoration	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=water-restoration&city=York&ref=e2c741b4-9bfb-3733-a1c2-2c59ad49ef69
info@electricsandmore.co.uk	Electrics	Electrics and More, Midlands Ltd	stoke-on-trent	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=stoke-on-trent&ref=7c090010-8fe5-344a-a908-4d21015b871d
info@lioncroftvehiclerecovery.co.uk	Lioncroft	Lioncroft Vehicle Recovery	Sutton Coldfield	breakdown	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=breakdown&city=Sutton%20Coldfield&ref=900b1711-8006-3ba9-b37d-79dcc5a0309d
info@elykeycutting.co.uk	Ely	Ely Master Locksmiths	Ely	locksmith	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=locksmith&city=Ely&ref=3acd62f8-ef1d-374c-8307-f62853e0bea9
sales@acedoubleglazing.co.uk	Ace	Ace Double Glazing Ltd	Plymouth	Glazier	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=Glazier&city=Plymouth&ref=0c40a3e1-4b0a-3833-b2da-6356ce44e03f
info@michaelwhiteelectrical.co.uk	Michael	Michael White Electrical Services	Brighton	Electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=Electrician&city=Brighton&ref=0426859a-7fc5-3070-b329-7067eb31cf78
info@hflbuildingsolutions.co.uk	HFL	HFL Building Solutions Oldham	Oldham	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Oldham&ref=c10c6760-fe6a-4e20-9b3c-623bc00f8728
info@emergency-plumberguildford.co.uk	Emergency	Emergency Plumbing Services Guildford 24HR	Guildford	plumber	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=plumber&city=Guildford&ref=88ada54e-4a0e-404d-a653-2235ef48f281
info@shrewsburylocks.co.uk	Professional	Professional Locksmiths Shrewsbury	Shrewsbury	locksmith	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=locksmith&city=Shrewsbury&ref=b94efff3-635d-3768-a197-fa5fcf9c414c
enquiries@drainklear.co.uk	Drain	Drain Klear	Ayr	drain-specialist	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=drain-specialist&city=Ayr&ref=00000000-0000-4000-a000-0000648d2e8c
info@cool-it-refrigeration.co.uk	Cool	Cool IT Refrigeration	Belfast	HVAC	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=HVAC&city=Belfast&ref=2d9865ec-08d5-33d3-a6e5-7459a8c42171
info@greenmangroup.org	Green	Green Man Environmental Services Ltd	Newport (Wales)	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=Newport%20(Wales)&ref=00000000-0000-4000-a000-00002afcdb82
info@reactive8emergencyservices.co.uk	Reactiv8	Reactiv8 Emergency Services Bolton	Bolton	water-restoration	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=water-restoration&city=Bolton&ref=ba01e2a1-58e9-4739-9ecc-17833aade9a8
info@plumbersayr.com	McLellan	McLellan Plumbers	Ayr	plumber	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=plumber&city=Ayr&ref=00000000-0000-4000-a000-0000405b12fd
info@southend-on-seawindowrepair.co.uk	Southend-on-Sea	Southend-on-Sea Glass Specialists	Southend-on-Sea	glazier	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=glazier&city=Southend-on-Sea&ref=fb14c6c3-eae4-3c66-b100-2e1b84e852cb
a1drainmaster@yahoo.co.uk	A1	A1 Drainmaster	South Shields	drain-specialist	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=drain-specialist&city=South%20Shields&ref=00000000-0000-4000-a000-00005ecc1d9b
business@nintendoswitch.com.cn	Switch	Switch electrical & building contractors	Cheltenham	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=Cheltenham&ref=e870e523-48d4-3495-892f-daa6832ec868
gbglass@mail.com	GB	GB Glass Products Ltd	Gateshead	glazier	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=glazier&city=Gateshead&ref=00000000-0000-4000-a000-00005930c234
info@manchesterlocks.co.uk	Manchester	Manchester Locksmith Services	Manchester	locksmith	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=locksmith&city=Manchester&ref=09b37f69-2ffa-326e-8a79-6631b10fd474
admin@hdairconditioning.com	H&D	H&D Air Conditioning	Brighton	HVAC	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=HVAC&city=Brighton&ref=f1c071c1-2135-3e07-a6a6-c592f0842f65
ladmin@bmsi.co.uk	B	B M S I	Maidenhead	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=Maidenhead&ref=00000000-0000-4000-a000-0000285bb6d5
n.hughes@rainbowrestoration.co.uk	Rainbow	Rainbow Restoration Glasgow East	Glasgow	water-restoration	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=water-restoration&city=Glasgow&ref=67fa6403-a3b0-4fd0-88ca-30de893a5265
sales@europeanglass.co.uk	European	European Toughened Glass Manchester	Macclesfield	glazier	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=glazier&city=Macclesfield&ref=00000000-0000-4000-a000-000077ee6978
info@highwycombeboilerrepairgasengineers.co.uk	High	High Wycombe Boiler Repair & Gas Engineers	High Wycombe	Gas Engineer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=Gas%20Engineer&city=High%20Wycombe&ref=b58074b6-b070-3bcd-a832-3755e6fcc01d
darrenscottrph@btinternet.com	Reading	Reading Plumbing and Heating	Reading	Plumber	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=Plumber&city=Reading&ref=e4b6af68-40a7-361a-817b-b8c18811323b
info@simplyenergy.co.uk	Trident	Trident Heating & Electrics Ltd	Beeston	gas-engineer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=gas-engineer&city=Beeston&ref=00000000-0000-4000-a000-0000332ff06b
office@brightonplumbers.co.uk	Safe	Safe Gas Plumbing & Electrics	Brighton	Gas Engineer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=Gas%20Engineer&city=Brighton&ref=968610fc-801d-3049-a7ab-bc933376ac96
info@ballairconditioning.co.uk	Ball	Ball Air Conditioning	Milton Keynes	HVAC	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=HVAC&city=Milton%20Keynes&ref=5e54197c-579f-3274-8fa7-56d7df2842d6
info@kayselectrical-services.co.uk	Kays	Kays Electrical Services	Lytham St Annes	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=Lytham%20St%20Annes&ref=00000000-0000-4000-a000-0000403514fe
info@all-seasons-roofing.co.uk	All	All Seasons Roofing	Wrexham	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=Wrexham&ref=00000000-0000-4000-a000-00004616dc6f
dsroofingyork@outlook.com	DSR	DSR Roofing York Support	York	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=York&ref=227c4a08-a116-40b5-a22c-85d9c1a8a987
enquiries@rkelectricalltd.co.uk	R	R K Electrical Services Ltd	Chesterfield	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=Chesterfield&ref=00000000-0000-4000-a000-0000356cd1da
office@dobsonandsurrey.co.uk	Dobson	Dobson & Surrey Ltd	South Shields	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=South%20Shields&ref=00000000-0000-4000-a000-000003fe237d
kc-locksmith@hotmail.com	K	K C Locksmith Services Ltd	Perth	locksmith	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=locksmith&city=Perth&ref=00000000-0000-4000-a000-00006d52457d
info@completebuilding-services.co.uk	Complete	Complete Building Services Swindon	Swindon	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Swindon&ref=767f18d7-0f1b-487a-8fab-d65daa2d600d
info@mcadamroofing.co.uk	McAdam	McAdam Roofing Ltd	Birkenhead	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=Birkenhead&ref=00000000-0000-4000-a000-00000cc15fdd
info@canterburydrainunblocking.co.uk	Canterbury	Canterbury Drain Solutions	Canterbury	drain-specialist	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=drain-specialist&city=Canterbury&ref=764aef9a-04e3-329f-88d4-a45a09d01dcc
thistleroofing@icloud.com	Thistle	Thistle Roofing	Stirling	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=Stirling&ref=00000000-0000-4000-a000-00004a77cb22
v.henderrson@hotmail.co.uk	3	3 Flow Drainage	Canvey Island	drain-specialist	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=drain-specialist&city=Canvey%20Island&ref=00000000-0000-4000-a000-00003b39588e
info@rustypipesemergencyplumbercrewe.co.uk	Rusty	Rusty Pipes Plumbing	Crewe	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=Crewe&ref=4f62d2f3-5e12-41a3-8e60-1b5d429c7119
info@carbreakdownservice.co.uk	Car	Car Breakdown Service Burgess Hill experts	Burgess Hill	breakdown	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=breakdown&city=Burgess%20Hill&ref=0ec270a9-ab7c-4cab-bc9a-b423dc8e3da3
info@apexhomecontractorsltd.co.uk	Apex	Apex Home Contractors Ltd London 24HR	London	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=London&ref=c8e3e9c6-b013-44d3-876c-8b36ece1d287
info@robinsonsfs.com	Robinsons	Robinsons Facilities Middlesbrough	Middlesbrough	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Middlesbrough&ref=e7031d98-e59b-431a-9f72-b4f16c66b173
gerrardsroofing@gmail.com	Gerrard's	Gerrard's Roofing Liverpool 24HR	Liverpool	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=Liverpool&ref=2eae81c7-3e9b-4778-bf6e-861260b27677
info@manchesterbreakdown.co.uk	Manchester	Manchester Breakdown Services Ltd	Manchester	breakdown	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=breakdown&city=Manchester&ref=6c9b398d-1bff-4ca7-914a-b6e800f2d64b
info@arthurpadgett.com	Padgett	Padgett Plumbers	Burnley	gas-engineer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=gas-engineer&city=Burnley&ref=00000000-0000-4000-a000-00000355173b
info@yell.com	Luk	Luk Recovery Leeds 24/7	Leeds	breakdown	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=breakdown&city=Leeds&ref=a4c62ef3-f7cf-40bc-aa5b-2aecb46e0262
info@ensureelectrical.co.uk	Ensure	Ensure Electrical Contractors	Preston	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=Preston&ref=41be18ff-8092-3895-97e6-59265f9053c4
expertlocksmiths@hotmail.co.uk	West	West Bromwich Locksmiths	West Bromwich	locksmith	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=locksmith&city=West%20Bromwich&ref=00000000-0000-4000-a000-00002fdc614d
info@remingtongas.co.uk	Remington	Remington Gas Services	West Bromwich	gas-engineer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=gas-engineer&city=West%20Bromwich&ref=00000000-0000-4000-a000-000030f71ab9
allen.shaun@hotmail.co.uk	Shaun	Shaun Allen Electrical Services	Truro	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=Truro&ref=e86c938d-f688-3753-b677-112c9601b352
info@mitchellandrewbuilding.co.uk	Mitchell	Mitchell & Andrew Building Services	Truro	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Truro&ref=c8a9c9ed-7836-38c6-8e08-cc2895f4a1de
info@nottsroofingcontractors.co.uk	Notts	Notts Roofing Contractors Ltd Beeston Support	Beeston	roofer	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=roofer&city=Beeston&ref=6cdf67a1-ba32-4eef-9c87-7dfac487201c
info@shanleyacs.com	Shanley	Shanley a C S Ltd	Barrow-in-Furness	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=Barrow-in-Furness&ref=00000000-0000-4000-a000-0000060841e2
info@no1drainsaberdeen.co.uk	No.1	No.1 Drains Aberdeen Ltd	Aberdeen	drain-specialist	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=drain-specialist&city=Aberdeen&ref=d94a7b25-bba9-3490-b03d-b6a62f2b74c1
sales@balmore-ltd.co.uk	Balmore	Balmore Specialist Contracts Glasgow	Glasgow	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Glasgow&ref=b931a1e3-1fc7-429e-a69c-0373ffffea1e
info@lakeslocks.co.uk	Lake	Lake District Mobile Locksmith	Workington	locksmith	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=locksmith&city=Workington&ref=00000000-0000-4000-a000-000036d652d3
info@thamesfloodrestoration.co.uk	Thames	Thames Flood Restoration	Westminster	water-restoration	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=water-restoration&city=Westminster&ref=0e9f5293-f4fe-3936-b187-f8d650cce7de
info@nwreno.co.uk	North	North West Home Renovations	Wigan	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Wigan&ref=2ace8f41-9d50-3bcc-943c-8c9d421c2881
devlinelectrics@gmail.com	Devlin	Devlin Electrics	coventry	electrician	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=electrician&city=coventry&ref=18a7f441-4a24-3f4d-9ecb-f864999b92a5
enquiries@kirkdalebuildings.co.uk	Kirkdale	Kirkdale Buildings Ltd	Leamington Spa	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Leamington%20Spa&ref=00000000-0000-4000-a000-000015ed3fd1
edu.uk@texa.com	Texa	Texa UK Ltd	Whitehaven	hvac	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=hvac&city=Whitehaven&ref=00000000-0000-4000-a000-00003cccbdaa
privacy@centrica.com	Dyno	Dyno	Lowestoft	drain-specialist	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=drain-specialist&city=Lowestoft&ref=00000000-0000-4000-a000-0000772b30c0
info@buildingbeautifulhomes.co.uk	Analytic	Analytic Building Contractors	Kingston	builder	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=builder&city=Kingston&ref=00000000-0000-4000-a000-000000c8ec64
info@glasgowplumbingheating.com	Glasgow	Glasgow Plumbing And Heating 24/7 Specialists	Glasgow	plumber	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=plumber&city=Glasgow&ref=4bc23770-92a2-4b59-afa7-0b70de5e9e88
queries@jbplumbing.co.uk	JB7	JB7 Plumbing and Heating Ltd Manchester 24HR	Manchester	plumber	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=plumber&city=Manchester&ref=ebae6cdb-1cde-4a28-a404-d8110a9e66d2
enquiries@vikingsbuildingsolutionsltd.co.uk	Vikings	Vikings Building Solutions Coventry 24HR	Coventry	plumber	https://emergencytradesmen.net/pricing?utm_source=gmail_mailmerge&utm_campaign=batch_1_manual&utm_medium=email&trade=plumber&city=Coventry&ref=b080b405-0978-4dae-ab6e-1b323e0b8c24`;
const blob = new Blob([data], {type: 'text/plain'});
const clipboardItem = new ClipboardItem({'text/plain': blob});
navigator.clipboard.write([clipboardItem]).then(() => {
  document.execCommand('paste');
  console.log('All 100 rows pasted successfully');
}).catch(err => console.error('Clipboard error:', err));
