-- Reliable blog-to-social queue. Content generation and provider publishing run
-- in the server-side worker; this migration owns detection, idempotency, state,
-- scheduling defaults, audit events, and approval/failure alerts.

ALTER TABLE public.social_accounts
  DROP CONSTRAINT IF EXISTS social_accounts_platform_check;

ALTER TABLE public.social_accounts
  ADD CONSTRAINT social_accounts_platform_check
  CHECK (platform IN ('facebook', 'instagram', 'tiktok', 'pinterest', 'linkedin', 'x')),
  ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true;

ALTER TABLE public.social_campaigns
  ADD COLUMN IF NOT EXISTS trend_status text NOT NULL DEFAULT 'pending'
    CHECK (trend_status IN ('pending', 'running', 'complete', 'skipped', 'failed')),
  ADD COLUMN IF NOT EXISTS quality_status text NOT NULL DEFAULT 'pending'
    CHECK (quality_status IN ('pending', 'passed', 'failed')),
  ADD COLUMN IF NOT EXISTS quality_score integer
    CHECK (quality_score IS NULL OR quality_score BETWEEN 0 AND 50),
  ADD COLUMN IF NOT EXISTS requires_approval boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_error text,
  ADD COLUMN IF NOT EXISTS next_attempt_at timestamptz,
  ADD COLUMN IF NOT EXISTS processing_started_at timestamptz,
  ADD COLUMN IF NOT EXISTS processing_completed_at timestamptz;

ALTER TABLE public.social_publications
  ADD COLUMN IF NOT EXISTS content_hash text,
  ADD COLUMN IF NOT EXISTS quality_score integer
    CHECK (quality_score IS NULL OR quality_score BETWEEN 0 AND 50),
  ADD COLUMN IF NOT EXISTS quality_report jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS generated_at timestamptz,
  ADD COLUMN IF NOT EXISTS reviewed_at timestamptz,
  ADD COLUMN IF NOT EXISTS approved_at timestamptz;

CREATE TABLE IF NOT EXISTS public.social_automation_settings (
  id text PRIMARY KEY DEFAULT 'default' CHECK (id = 'default'),
  enabled boolean NOT NULL DEFAULT true,
  daily_publish_time time NOT NULL DEFAULT '18:30:00',
  schedule_timezone text NOT NULL DEFAULT 'Europe/London',
  minimum_quality_score integer NOT NULL DEFAULT 35
    CHECK (minimum_quality_score BETWEEN 0 AND 50),
  approval_mode text NOT NULL DEFAULT 'safety_only'
    CHECK (approval_mode IN ('always', 'safety_only', 'none')),
  trend_research_enabled boolean NOT NULL DEFAULT true,
  max_publish_attempts integer NOT NULL DEFAULT 3
    CHECK (max_publish_attempts BETWEEN 1 AND 10),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

INSERT INTO public.social_automation_settings (id)
VALUES ('default')
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.social_automation_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_id uuid REFERENCES public.social_campaigns(id) ON DELETE CASCADE,
  publication_id uuid REFERENCES public.social_publications(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  event_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.social_automation_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id uuid REFERENCES public.social_campaigns(id) ON DELETE CASCADE,
  publication_id uuid REFERENCES public.social_publications(id) ON DELETE CASCADE,
  severity text NOT NULL CHECK (severity IN ('info', 'warning', 'error')),
  alert_type text NOT NULL,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'acknowledged', 'resolved')),
  dedupe_key text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  resolved_at timestamptz
);

CREATE INDEX IF NOT EXISTS social_campaigns_processing_idx
  ON public.social_campaigns (state, next_attempt_at, created_at);
CREATE INDEX IF NOT EXISTS social_events_campaign_idx
  ON public.social_automation_events (campaign_id, created_at DESC);
CREATE INDEX IF NOT EXISTS social_alerts_open_idx
  ON public.social_automation_alerts (status, severity, created_at DESC)
  WHERE status = 'open';
CREATE UNIQUE INDEX IF NOT EXISTS social_publications_content_hash_idx
  ON public.social_publications (account_id, content_hash)
  WHERE content_hash IS NOT NULL
    AND status NOT IN ('failed', 'cancelled');

ALTER TABLE public.social_automation_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_automation_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_automation_alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage social automation settings" ON public.social_automation_settings;
CREATE POLICY "Admins manage social automation settings"
ON public.social_automation_settings
FOR ALL TO authenticated
USING ((select public.is_admin()))
WITH CHECK ((select public.is_admin()));

DROP POLICY IF EXISTS "Admins read social automation events" ON public.social_automation_events;
CREATE POLICY "Admins read social automation events"
ON public.social_automation_events
FOR SELECT TO authenticated
USING ((select public.is_admin()));

DROP POLICY IF EXISTS "Admins manage social automation alerts" ON public.social_automation_alerts;
CREATE POLICY "Admins manage social automation alerts"
ON public.social_automation_alerts
FOR ALL TO authenticated
USING ((select public.is_admin()))
WITH CHECK ((select public.is_admin()));

GRANT SELECT, INSERT, UPDATE, DELETE ON public.social_automation_settings TO authenticated;
GRANT SELECT ON public.social_automation_events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.social_automation_alerts TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.social_automation_events_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.next_social_publish_at(
  base_time timestamptz,
  local_publish_time time,
  timezone_name text
)
RETURNS timestamptz
LANGUAGE plpgsql
STABLE
SET search_path = ''
AS $$
DECLARE
  local_base timestamp;
  local_target timestamp;
BEGIN
  local_base := base_time AT TIME ZONE timezone_name;
  local_target := date_trunc('day', local_base) + local_publish_time;
  IF local_target <= local_base THEN
    local_target := local_target + interval '1 day';
  END IF;
  RETURN local_target AT TIME ZONE timezone_name;
END;
$$;

CREATE OR REPLACE FUNCTION public.enqueue_social_campaign_for_post()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  settings_row public.social_automation_settings%ROWTYPE;
  campaign_id uuid;
  post_market text;
  publish_time timestamptz;
  base_url text;
BEGIN
  IF NEW.published IS DISTINCT FROM true OR NEW.published_at IS NULL THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE'
     AND OLD.published IS TRUE
     AND OLD.published_at IS NOT DISTINCT FROM NEW.published_at THEN
    RETURN NEW;
  END IF;

  SELECT * INTO settings_row
  FROM public.social_automation_settings
  WHERE id = 'default';

  IF NOT FOUND OR settings_row.enabled IS NOT TRUE THEN
    RETURN NEW;
  END IF;

  post_market := CASE WHEN NEW.slug LIKE '%-us' THEN 'US' ELSE 'GB' END;
  base_url := CASE
    WHEN post_market = 'US' THEN 'https://emergencycontractors.net/blog/'
    ELSE 'https://emergencytradesmen.net/blog/'
  END;
  publish_time := public.next_social_publish_at(
    NEW.published_at,
    settings_row.daily_publish_time,
    settings_row.schedule_timezone
  );

  INSERT INTO public.social_campaigns (
    source_post_id,
    market,
    state,
    idempotency_key,
    safety_review_required,
    requires_approval,
    scheduled_at
  )
  VALUES (
    NEW.id,
    post_market,
    'detected',
    'blog:' || NEW.slug || ':social-v1',
    false,
    settings_row.approval_mode = 'always',
    publish_time
  )
  ON CONFLICT (idempotency_key) DO UPDATE SET
    scheduled_at = COALESCE(public.social_campaigns.scheduled_at, EXCLUDED.scheduled_at),
    updated_at = timezone('utc', now())
  RETURNING id INTO campaign_id;

  INSERT INTO public.social_publications (
    campaign_id,
    account_id,
    status,
    destination_url,
    media_url,
    scheduled_at,
    schedule_timezone
  )
  SELECT
    campaign_id,
    account.id,
    'draft',
    base_url || NEW.slug,
    NEW.cover_image,
    publish_time,
    settings_row.schedule_timezone
  FROM public.social_accounts AS account
  WHERE account.market = post_market
    AND account.enabled
  ON CONFLICT (campaign_id, account_id) DO NOTHING;

  INSERT INTO public.social_automation_events (campaign_id, event_type, event_data)
  VALUES (
    campaign_id,
    'blog_detected',
    jsonb_build_object(
      'post_id', NEW.id,
      'slug', NEW.slug,
      'published_at', NEW.published_at,
      'scheduled_at', publish_time
    )
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS enqueue_social_campaign_after_publish ON public.posts;
CREATE TRIGGER enqueue_social_campaign_after_publish
AFTER INSERT OR UPDATE OF published, published_at ON public.posts
FOR EACH ROW
EXECUTE FUNCTION public.enqueue_social_campaign_for_post();

-- Existing posts are deliberately not backfilled. The trigger starts with new
-- publish events so older blogs and their successful creative remain untouched.
